In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("IMDB_Dataset.csv")

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [5]:
df.shape

(50000, 2)

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df.shape

(49582, 2)

## Pre - Processing

In [8]:
### 1. Converting to lowercase

df["review"] = df["review"].str.lower()

In [9]:
### 2. Removing the URLs

import re

# sample_text = "abc is the word , abc" # abs => xyz

# new_text = re.sub( "abc" , "xyz"  , sample_text)

In [10]:
def remove_url(text):

    text = re.sub( r"http\S+" , "" , text) # (pattern , repl , string)
    return text

df["review"] = df["review"].apply(remove_url)

In [11]:
### 3. Removing punctuations

def remove_punctuations(text):

    text = re.sub( r"[^A-Za-z0-9\s]" , "" , text) # A-Z a-z 0-9 \s 
    return text

df["review"] = df["review"].apply(remove_punctuations)

In [12]:
### 4. Removing HTML

def remove_HTML(text):

    text = re.sub( r"<,*?>" , "" , text) 
    return text

df["review"] = df["review"].apply(remove_HTML)

In [13]:
### 5. Removing the Stopwords

import nltk

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ohhaa\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ohhaa\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ohhaa\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [14]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [15]:
sample_text = "I like coding in cpp"
tokens = word_tokenize(sample_text)
print(tokens)

['I', 'like', 'coding', 'in', 'cpp']

In [16]:
stop_words = stopwords.words("english")
#stop_words = set(stopwords.words("english"))

def remove_stopwords(text):

    tokens = word_tokenize(text)


    for word in tokens :
        if word in stop_words:
            text = text.replace(word,"")

    return text

df["review"] = df["review"].apply(remove_stopwords)

In [17]:
df.head()

                                              review sentiment
0  e    revewers  nted   wtchg  1 oz epode ll  ho...  positive
1   wderful ltle producti br br  filming techniqu...  positive
2   thought ths   wderful wy  spend tme   o hot s...  positive
3  bsclly res  fmly   lttle boy jke thks res  zom...  negative
4  petter mtte love   time  mey   vully stunng fi...  positive

In [18]:
### 6. Steming

# running - run 
# played - play

# PorterSteming Algorithm 

from nltk.stem import PorterStemmer

In [19]:
ps = PorterStemmer()

def steming(text):

    stemed_words = []
    tokens = word_tokenize(text)
    for token in tokens : 

        stemed_token = ps.stem(token)
        stemed_words.append(stemed_token)

    return " ".join(stemed_words)

df["review"] = df["review"].apply(steming)

In [20]:
### 7. Encoding

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["sentiment"] = le.fit_transform(df["sentiment"])

In [21]:
y = df["sentiment"]
print(y)

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

In [22]:
df.head()

                                              review  sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...          1
1  wder ltle producti br br film techniqu unssum ...          1
2  thought th wder wy spend tme o hot summer week...          1
3  bsclli re fmli lttle boy jke thk re zomb close...          0
4  petter mtte love time mey vulli stunng film wt...          1

In [23]:
### 8. Vectorization

from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(max_features=5000)

x = tf.fit_transform(df["review"])

In [24]:
x.shape

(49582, 5000)

In [25]:
x

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4057140 stored elements and shape (49582, 5000)>

In [26]:
print(x)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4057140 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3538)	0.05515484681268887
  (0, 2868)	0.09361182809242374
  (0, 4940)	0.11467310366614668
  (0, 3002)	0.47200539890110405
  (0, 1275)	0.1357698919196183
  (0, 2289)	0.049500237517476293
  (0, 1933)	0.0791260308382
  (0, 3550)	0.0963974330192639
  (0, 1362)	0.06162489377343992
  (0, 1963)	0.061560444992697486
  (0, 219)	0.08588920995304898
  (0, 1620)	0.0738170550485134
  (0, 4369)	0.041994187696759305
  (0, 4171)	0.17799685402440263
  (0, 3693)	0.033532198172897175
  (0, 4737)	0.26798942924092045
  (0, 3805)	0.04427609784380831
  (0, 4769)	0.05877405881441711
  (0, 1739)	0.037520883911174724
  (0, 4497)	0.07614066339174266
  (0, 3857)	0.17537900435282314
  (0, 1630)	0.06142445471882175
  (0, 1862)	0.07433134577032253
  (0, 3329)	0.06406818508428483
  (0, 3332)	0.0844754682576354
  :	:
  (49581, 4890)	0.10682334916138103
  (49581, 1542)	0.17584072573791829
  (49581, 4494)	0.09410069396961679
  (49581, 434)	0.11251655954741112
  (49581, 4277)	0.10905956327445408
  (49581, 1958)	0.0999074542943991
  (49581, 555)	0.08424218838425554
  (49581, 2187)	0.14180348667063264
  (49581, 2217)	0.09535602544797335
  (49581, 4347)	0.17508214877875983
  (49581, 4629)	0.1157123083349983
  (49581, 3647)	0.087334023293812
  (49581, 4734)	0.12354122837064464
  (49581, 1977)	0.1279546327938257
  (49581, 527)	0.1247934452922504
  (49581, 2621)	0.17341357547872566
  (49581, 4458)	0.16002233459530202
  (49581, 2174)	0.18983797727912208
  (49581, 4033)	0.20100044911463438
  (49581, 341)	0.14784964476913964
  (49581, 2695)	0.1740080872946952
  (49581, 439)	0.13323526536564564
  (49581, 4980)	0.15095820717373318
  (49581, 1764)	0.15815315432712562
  (49581, 3489)	0.1519741559925848

# Dataset & Data Loaders

In [27]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(
    x , y , test_size=0.2 , random_state=42
)

In [28]:
x_train.shape

(39665, 5000)

In [29]:
x_test.shape

(9917, 5000)

In [30]:
import torch
print(torch.__version__)

from torch.utils.data import Dataset, DataLoader , TensorDataset

2.13.0+cu130

In [31]:
x_train = x_train.toarray()
x_test = x_test.toarray()

In [33]:
train_set = TensorDataset(
	torch.from_numpy(x_train).float() ,
    torch.from_numpy(y_train.values).float()
)

test_set = TensorDataset(
	torch.from_numpy(x_test).float() ,
    torch.from_numpy(y_test.values).float()
)

In [34]:
train_loader = DataLoader(train_set , shuffle=True , batch_size = 64)
test_loader = DataLoader(test_set , shuffle=True , batch_size = 64)

## BUILD Our RNN

In [37]:
import torch.nn as nn 
import torch.optim as optim

In [39]:
class RNN(nn.Module): # many to one RNN architecture

    def __init__(self , input_size , hidden_size = 128 , num_layers = 1):
        super().__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers

        # RNN layer
        self.rnn = nn.RNN( input_size , hidden_size, num_layers , batch_first=True)

        # fully connected layer
        self.fc = nn.Linear(hidden_size,1)

    def forward(self,x):

        # optional => shape( num of layers , batch size , hidden size)
        h0 = torch.zeros(self.num_layers , x.size(0) , self.hidden_size)

        out , _ = self.rnn(x,h0)
        # 1st value = hidden state of all the timesteps => (batch , seq_len , hidden size)
        # 2nd value = final hidden state of last timesteps

        out = self.fc(out[: , -1 , :])

        return out

In [40]:
input_size = x_train.shape[1]

model = RNN(input_size)

criterion = nn.BCELoss()

optimizer = optim.Adam(model.parameters())

## Training the RNN

In [ ]:
# unsqueeze , squeeze

In [43]:
epochs = 10 

for epoch in range(epochs):

    model.train()

    for xb , yb in train_loader:

        optimizer.zero_grad()

        xb = xb.unsqueeze(1) # add 1 singleton direction

        outputs = model(xb) # (batch size , 1)

        outputs = torch.sigmoid(outputs.squeeze()) # (batch size , ) => probability

        loss = criterion(outputs, yb) # compute loss
        loss.backward() # backprop
        optimizer.step() # weights update
    print(f"epoch = {epoch+1}/{epochs} and loss = {loss.item()}")

epoch = 1/10 and loss = 0.10965632647275925
epoch = 2/10 and loss = 0.32589438557624817
epoch = 3/10 and loss = 0.518767237663269
epoch = 4/10 and loss = 0.22055509686470032
epoch = 5/10 and loss = 0.11451657861471176
epoch = 6/10 and loss = 0.32809752225875854
epoch = 7/10 and loss = 0.18806856870651245
epoch = 8/10 and loss = 0.18732351064682007
epoch = 9/10 and loss = 0.17235007882118225
epoch = 10/10 and loss = 0.12316884845495224

In [45]:
# evaluate 

model.eval()

with torch.no_grad():

    correct_vals = 0 
    tot_vals = 0

    for xb , yb in test_loader:

        xb = xb.unsqueeze(1)

        outputs = model(xb)
        predicted = ( torch.sigmoid(outputs.squeeze()) > 0.5 ).float()

        tot_vals += yb.size(0)
        correct_vals += (predicted==yb).sum().item()

    print(f"Accuracy = {correct_vals/tot_vals*100}")

Accuracy = 85.21730362004638